# Generated by Django 5.1.3 on 2025-02-01 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0001_initial'),
        ('products', '0001_initial'),
        ('specifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='specification',
            unique_together={('parameter', 'product')},
        ),
    ]
